src/calendar_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.calendar_list, name="calendar_list"),
	url(r'^sync$',views.sync_calendar_list, name="sync_calendar_list"),
	url(r'^(?P<calendar_id>.*)/sync$',views.sync_events, name="sync_events"),
	url(r'^(?P<calendar_id>.*)/events/$', views.calendar_events, name='calendar_events'),
]

src/profileapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.index, name="update"),
	# url(r'^event$',views.EventListView.as_view(), name="event_index"),
]

src/sandbox/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from calendar_app.views import oauth2callback
import allauth
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='about.html')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include("profileapp.urls", namespace='profile')),
    url(r'^venue/', include("venueapp.urls", namespace='venue')),
    url(r'^event/', include("workshop.urls", namespace='workshop')),
    url(r'^calendar/', include("calendar_app.urls", namespace='calendar_app')),
    url(r'^oauth2callback/', oauth2callback, name='auth_uri'),

]

src/venueapp/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
	url(r'^$', views.VenueListView.as_view(), name='index'),
	url(r'^my/$', login_required(views.MyVenueListView.as_view()), name='self_created'),
	url(r'^create$', views.create, name='create'),
	url(r'^(?P<pk>[0-9]+)/$',views.VenueDetailView.as_view(), name="detail"),
	url(r'^(?P<pk>[0-9]+)/edit$',views.venue_update, name="edit"),
]

src/templates/about.html
{% extends "base.html" %}

{% block title %} Events List | {{ block.super }} {% endblock %}

{% block content %}
	<div class="row">
		<center>
			<div class="btn-group">
				<a class="btn btn-default" href="{% url 'calendar_app:calendar_list' %}">Calendar List</a>
				<a class="btn btn-default" href="{% url 'calendar_app:sync_calendar_list' %}">Sync Calendar List</a>
			</div>
		</center>
	</div>
	<hr>
	<div class="col-md-6 col-md-offset-3 jumbotron">
		<h2 class="text-center">Welcome To SandBox</h2>
		<hr>
		<h3><strong>About :</strong></h3>
		<p class="text-justify">
			It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' 
		</p>
	</div>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>{% block title %}SandBox {% endblock %}</title>

    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>

</head>
<body>
    {% load account %}
    <nav class="navbar navbar-default">
        <div class="container">
            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#TopNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-glass">  </span> SandBox</a>
            </div>
            <div class="collapse navbar-collapse" id="TopNavBar">
                <ul class="nav navbar-nav">
                    <li>
                        {# request.resolver_match.url_name #}
                        <a href="/">
                            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;
                            Home
                        </a>
                    </li>
                    <li class="" >
                        <a href="{% url 'workshop:index' %}">
                            <span class="glyphicon glyphicon-time" aria-hidden="true"></span>&nbsp;
                            Events
                        </a>
                    </li>
                    <li class="" >
                        <a href="{% url 'venue:index' %}">
                            <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>&nbsp;
                            Venue
                        </a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">
                                {{ request.user.username }}
                                <span class="caret"></span>
                            </a>
                            
                            

                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{% url 'profile:update' %}">
                                        Update Profile
                                    </a>
                                </li>
                                {% if user.user_member.isOrganizer%}
                                <li>
                                    <a href="{% url 'workshop:self_created' %}">
                                        My Events
                                    </a>
                                </li>
                                {% endif %}
                                {% if user.user_member.isVenue %}
                                <li>
                                    <a href="{% url 'venue:self_created' %}">
                                        My Venue
                                    </a>
                                </li>
                                {% endif %}


                                <li role="separator" class="divider"></li>
                                <!-- <li class="dropdown-header">Logout</li> -->
                                <li><a href="/accounts/logout">Logout</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li class="" >
                            <a id="google_login" href="/accounts/login">
                                Sign in
                            </a>
                        </li>
                    {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% include "messages_display.html" %}

        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script type="text/javascript">
        
        $('input').addClass('form-control');
        $('textarea').addClass('form-control');
        $('select').addClass('form-control');
        $('button').addClass('btn btn-primary');

    </script>

</body>
</html>

src/templates/messages_display.html
{% comment %}
	{% if messages %}
		<div class="alert alert-info">
			<ul class="message">
				{% for message in messages %}
					<li {%if message.tags %} class="{{ message.tags }}" {% endif %}}>
						-->{{ message.level }}<--
						{% if "html_safe" in message.tags %}
							{{ message|safe }}
						{% else %}
							{{ message }}
						{% endif %}
					</li>
				{% endfor %}
			</ul>
		</div>
	{% endif %}
{% endcomment %}


{% if messages %}
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
				{% for message in messages %}
					<div {%if message.tags %} class="text-center alert alert-{{ message.tags }}" {% endif %}>
						{{ message|safe }}
					</div>
				{% endfor %}
			</ul>
		</div>
	</div>
{% endif %}

{% if form.errors %}
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="alert alert-warning">
				{{ form.errors }}
			</div>
		</div>
	</div>
{%endif%}