src/sandbox/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from calendar_app.views import oauth2callback
import allauth
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='about.html')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include("profileapp.urls", namespace='profile')),
    url(r'^venue/', include("venueapp.urls", namespace='venue')),
    url(r'^event/', include("workshop.urls", namespace='workshop')),
    url(r'^calendar/', include("calendar_app.urls", namespace='calendar_app')),
    url(r'^oauth2callback/', oauth2callback, name='auth_uri'),

]

src/venueapp/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
	url(r'^$', views.VenueListView.as_view(), name='index'),
	url(r'^my/$', login_required(views.MyVenueListView.as_view()), name='self_created'),
	url(r'^create$', views.create, name='create'),
	url(r'^(?P<pk>[0-9]+)/$',views.VenueDetailView.as_view(), name="detail"),
	url(r'^(?P<pk>[0-9]+)/edit$',views.venue_update, name="edit"),
]

src/venueapp/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models


class Venue(models.Model):
	user = models.ForeignKey('profileapp.Member')
	venueName = models.CharField(max_length=500)
	summary = models.CharField(max_length=1000)
	website = models.URLField(blank=True)
	socialLink = models.URLField(blank=True)
	coverPhoto = models.ImageField(blank=True)
	logo = models.ImageField(blank=True)
	contactInfo = models.CharField(max_length=200,blank=True)
	email = models.EmailField(max_length=254)
	location = models.CharField(max_length=500)
	phone = models.CharField(max_length=15)
	confirmation = models.BooleanField(default=False)
	wifiAvailability = models.BooleanField(default=False)
	capacity = models.IntegerField(default=0)
	cateringAvailability = models.BooleanField(default=False)

	def __unicode__(self):
		return self.venueName

	def get_absolute_url(self):
		return reverse("venue:detail",kwargs = {"pk": self.id })

src/venueapp/forms.py
from django import forms
from .models import Venue

class VenueForm(forms.ModelForm):	
	class Meta:
		model = Venue
		fields = '__all__'

src/venueapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from .models import Venue
from .forms import VenueForm
from profileapp.models import Member
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from allauth.account.decorators import verified_email_required

class VenueListView(generic.ListView):
    template_name = 'venueapp/venue_list.html'
    context_object_name = 'venues'

    def get_queryset(self):
        return Venue.objects.all()

class VenueDetailView(generic.DetailView):
    model = Venue
    template_name = 'venueapp/venue_detail.html'

@verified_email_required
def create(request):
	form = VenueForm(request.POST or None)

	if form.is_valid():
		instance = form.save(commit = False)
		instance.save()
		messages.success(request, "Venue Added Successfully")
		return HttpResponseRedirect(instance.get_absolute_url())

	contex = {
		'form' : form,
		'heading' : "Add Venue"
	}
	return render(request,'venueapp/form.html',contex)

class MyVenueListView(generic.ListView):
    template_name = 'venueapp/venue_list.html'
    context_object_name = 'venues'

    def get_queryset(self):
        return Venue.objects.filter(user=self.request.user.user_member)

@verified_email_required
def venue_update(request, pk):
	#getting member object of current user
	user = Member.objects.filter(user=request.user)[0]

	if not user.isVenue:
		msg = """
			You are not a venue, become venue to create venue<br>
			To Become Venue go to <a href='%s'>link</a> and check on venue field
		""" % reverse('profile:update')
		messages.warning(request, msg)
		return HttpResponseRedirect(reverse('workshop:index'))


	instance = get_object_or_404(Venue, pk=pk)

	#checking of user is owener of event
	if instance.user != user:
		messages.warning(request, "You dont have permission to edit !!")
		return HttpResponseRedirect(reverse('venue:detail', kwargs={ 'pk':pk }))

	form = VenueForm(request.POST or None, request.FILES or None, instance = instance)

	if form.is_valid():
		instance = form.save(commit = False)
		instance.save()
		messages.success(request, "Updated Successfully")
		return HttpResponseRedirect(instance.get_absolute_url())
	
	contex = {
		'form' : form,
	}
	return render(request,'venueapp/form.html',contex)

src/templates/venueapp/calendar_event.html
{% extends "base.html" %}

{% block content %}
	{% if events %}
		{% for event in events %}
			Start : {{ event.start.dateTime }}<br>
			End : {{ event.end.dateTime }}<br>
			Summary : {{ event.summary }}<br>
			<a href="{{ event.htmlLink }}">link to google calendar</a>
			<hr>
		{% endfor %}
	{% else %}
		No Events Yet
	{% endif %}
	
{% endblock %}

src/templates/venueapp/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block head_extra %}
{{ form.media }}
{%endblock head_extra %}


{% block title %} Create Event | {{ block.super }} {% endblock %}

{% block content %}

	{# block.super renders the superblock content #}
	{{ block.super }}
	
	<div class="col-md-10 col-md-offset-1">
		<h2>{{ heading }}</h2>
		<form action="" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form|crispy }}
			<button type="submit">Submit</button>
		</form>
	</div>
{% endblock %}

src/templates/venueapp/venue_detail.html
{% extends "base.html" %}

{% block title %} Events List | {{ block.super }} {% endblock %}

{% block content %}
	<div class="col-md-6 col-md-offset-3">
		<h1>{{ venue.venueName }}</h1>
		<hr>
		Venue Name : <strong>{{ venue.venueName }}</strong><br>
		Summary : {{ venue.summary }}<br>
		Email : {{ venue.email }}<br>
		Location : {{ venue.location }}<br>
		Phone : {{ venue.phone }}<br>
		Capacity : {{ venue.capacity }}<br>
	</div>
{% endblock %}

src/templates/venueapp/venue_list.html
{% extends "base.html" %}

{% block title %} Events List | {{ block.super }} {% endblock %}

{% block content %}
	{% if user.is_authenticated and user.user_member.isVenue %}
	<div class="row">
		<div class="col-md-offset-2 col-md-4">
			<a class="btn btn-primary btn-block" href="{% url 'venue:create'%}">Add Venue</a>
		</div>
	</div>
	<hr>
	{% endif %}

	<div class="row">
	{% if venues %}
		{% for venue in venues %}
			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						<a href="{% url 'venue:detail' venue.id %}">
						{{ venue.venueName }}
						</a>
					</div>
					<div class="panel-body">
						{{ venue.summary }}
					</div>
					{% if venue.user == user.user_member %}
					<div class="panel-footer">
						<a href="{% url 'venue:edit' venue.id %}" class="btn btn-default">
							Edit
						</a>
					</div>
					{% endif %}
				</div>
			</div>
		{% endfor %}
	{% else %}
		<p>No venue Yet</p>

	{% endif %}
	</div>
{% endblock %}