src/sandbox/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from calendar_app.views import oauth2callback
import allauth
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='about.html')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include("profileapp.urls", namespace='profile')),
    url(r'^venue/', include("venueapp.urls", namespace='venue')),
    url(r'^event/', include("workshop.urls", namespace='workshop')),
    url(r'^calendar/', include("calendar_app.urls", namespace='calendar_app')),
    url(r'^oauth2callback/', oauth2callback, name='auth_uri'),

]

src/workshop/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
	url(r'^$',views.EventListView.as_view(), name="index"),
	url(r'^my/$',login_required(views.MyEventListView.as_view()), name="self_created"),
	url(r'^(?P<pk>[0-9]+)/$',views.EventDetailView.as_view(), name="detail"),
	url(r'^(?P<pk>[0-9]+)/csv$',views.download_csv, name="csv"),
	url(r'^(?P<pk>[0-9]+)/edit$',views.event_update, name="edit"),
	url(r'^create$',views.event_create, name="create"),
	url(r'^(?P<pk>[0-9]+)/enroll$',views.enroll, name="enroll"),
]

src/workshop/models.py
from django.db import models
from django.core.urlresolvers import reverse
from profileapp.models import Member
from django.contrib.auth.models import User

class Event(models.Model):
	activityName = models.CharField(max_length=200)
	activityType =  models.CharField(max_length=200)
	schedule = models.DateTimeField(auto_now_add=False)
	venue = models.ForeignKey('venueapp.Venue')
	information = models.CharField(max_length=500,blank=True)
	content = models.TextField(blank=True)
	photo  = models.ImageField(blank=True)
	terms = models.TextField(blank=True)
	confirmation = models.BooleanField(default=False)
	cost = models.FloatField(default=0.0)
	user = models.ForeignKey('profileapp.Member')
	enrolled_users = models.ManyToManyField(User, blank=True)

	def __unicode__(self):
		return self.activityName

	def get_absolute_url(self):
		return reverse("workshop:detail",kwargs = {"pk": self.id })

src/workshop/forms.py
from django import forms
from .models import Event

class EventForm(forms.ModelForm):
	class Meta:
		model = Event
		exclude = ['user',]

src/workshop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail
from .forms import EventForm
from django.contrib import messages
from django.views import generic
from .models import Event #,EventEnrolment
from profileapp.models import Member
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from allauth.account.decorators import verified_email_required
import csv

@verified_email_required
def event_create(request):
	user = Member.objects.filter(user=request.user)[0]
	
	if not user.isOrganizer:
		msg = """
			You are not an organizer, become organizer to create events<br>
			To Become Organizer go to <a href='%s'>link</a> and check on organizer field
		""" % reverse('profile:update')
		messages.warning(request, msg)
		return HttpResponseRedirect(reverse('workshop:index'))

	form = EventForm(request.POST or None)

	if form.is_valid():
		instance = form.save(commit = False)
		instance.user = user
		instance.save()
		messages.success(request, "Created Successfully")
		return HttpResponseRedirect(instance.get_absolute_url())

	contex = {
		'form' : form,
		'heading' : "Add New Event"
	}
	return render(request,'workshop/form.html',contex)

@verified_email_required
def event_update(request,pk):

	#getting member object of current user
	user = Member.objects.filter(user=request.user)[0]

	if not user.isOrganizer:
		msg = """
			You are not an organizer, become organizer to create events<br>
			To Become Organizer go to <a href='%s'>link</a> and check on organizer field
		""" % reverse('profile:update')
		messages.warning(request, msg)
		return HttpResponseRedirect(reverse('workshop:index'))


	instance = get_object_or_404(Event, pk=pk)

	#checking of user is owener of event
	if instance.user != user:
		messages.warning(request, "You dont have permission to edit !!")
		return HttpResponseRedirect(reverse('workshop:detail', kwargs={ 'pk':pk }))

	form = EventForm(request.POST or None, request.FILES or None, instance = instance)

	if form.is_valid():
		instance = form.save(commit = False)
		instance.save()
		messages.success(request, "Updated Successfully")
		return HttpResponseRedirect(instance.get_absolute_url())
	
	contex = {
		'form' : form,
	}
	return render(request,'workshop/form.html',contex)
	
class EventListView(generic.ListView):
    template_name = 'workshop/event_list.html'
    context_object_name = 'events'

    def get_queryset(self):
        return Event.objects.all().order_by('-schedule')

class MyEventListView(generic.ListView):
    template_name = 'workshop/event_list.html'
    context_object_name = 'events'

    def get_queryset(self):
    	return Event.objects.filter(user=self.request.user.user_member)

class EventDetailView(generic.DetailView):
    model = Event
    template_name = 'workshop/event_detail.html'

@verified_email_required
def enroll(request, pk):
	event = Event.objects.get(pk=pk)
	enrolled_events = request.user.event_set.all()
	print enrolled_events

	if not event in enrolled_events:
		event.enrolled_users.add(request.user)
		event.save()
		messages.info(request, "Successfully enrolled for the event '%s'" % (event.activityName) )
		return redirect(reverse('workshop:index'))
	else:
		messages.info(request, "You have already enrolled for this event")
		return redirect(reverse('workshop:index'))

@verified_email_required
def download_csv(request, pk):
	event = get_object_or_404(Event, pk=pk)

	filename = event.activityName +"_id" + str(event.id) + ".csv"

	if request.user.user_member != event.user:
		messages.warning(request, "You dont have permission to access this url")
		return redirect(reverse('workshop:detail', kwargs={'pk' : event.pk }))

	enrolled_users = event.enrolled_users.all()
	if not enrolled_users:
		messages.info(request, "No user have enrolled yet")
		return redirect(reverse('workshop:detail', kwargs={'pk' : event.pk }))

	response = HttpResponse(content_type='text/csv')
	response['Content-Disposition'] = 'attachment; filename="%s"' % (filename)

	writer = csv.writer(response)
	
	writer.writerow(['Sr', 'Username', 'Email'])
	for i,enroll in enumerate(enrolled_users):
		writer.writerow([str(i+1), enroll.username , enroll.email])

	return response

src/templates/workshop/event_detail.html
{% extends "base.html" %}

{% block title %} Events List | {{ block.super }} {% endblock %}

{% block content %}
	{% if event.user != user.user_member %}
		<div>
		{% if event in user.event_set.all %}
				Already Enrolled
		{% else %}
			<a href="{% url 'workshop:enroll' event.id %}" class="btn btn-primary">
				Enroll Now
			</a>
		{% endif %}
		</div>
	{% endif %}
	
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1>{{ event.activityName }}</h1>
			<hr>
			Activity Name : <strong>{{ event.activityName }}</strong><br>
			Activity Type : {{ event.activityType }}<br>
			Venue : {{ event.venue }}<br>
			Info : {{ event.information }}<br>
			Schedule : {{ event.schedule }}<br>
			cost : {{ event.cost }}<br>
		</div>
	</div>
	
	{% if user.is_authenticated and event.user == user.user_member %}
	<hr>
	<div>
		<a href="{% url 'workshop:edit' event.id %}" class="btn btn-info">
			Edit
		</a>
	</div>
	<h2>Enrolled Users</h2>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			{% if event.enrolled_users.all %}
				<a href="{% url 'workshop:csv' event.pk %}">
					<span class="glyphicon glyphicon-download-alt">
					</span>
					Download as CSV
				</a>
				<br><br>
				<table class="table">
					<thead>
						<tr>
							<th>Sr.</th>
							<th>Name</th>
							<th>Email</th>
						</tr>
					</thead>
					<tbody>
						{% for user in event.enrolled_users.all %}
						<tr>
							<td>{{ forloop.counter }}</td>
							<td>{{ user.username }}</td>
							<td>{{ user.email }}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			{% else %} 
				No Enrollment yet
			{% endif %}
		</div>
	</div>
	{% endif %}

{% endblock %}

src/templates/workshop/event_list.html
{% extends "base.html" %}

{% block title %} Events List | {{ block.super }} {% endblock %}

{% block content %}
	{% if user.is_authenticated and user.user_member.isOrganizer%}
	<div class="row">
		<div class="col-md-offset-8 col-md-4">
			<a class="btn btn-primary btn-block" href="{% url 'workshop:create'%}">Add New Event</a>
		</div>
	</div>
	<br>
	{% endif %}
	
	<div class="row">
	{% if events %}
		{% for event in events %}
			<div class="col-md-4">
				
				{# if user is owner of event then use panel-warning#}
				{% if event.user == user.user_member %}
				<div class="panel panel-danger ">
				{% else %}
				<div class="panel panel-default">
				{% endif %}

					<div class="panel-heading">
						<a href="{% url 'workshop:detail' event.id %}">
						{{ event.activityName }}
						</a>
					</div>
					<div class="panel-body">
						{{ event.information }}
						<br>
						{{ event.schedule }}
					</div>
					{% if event.user == user.user_member %}
					<div class="panel-footer">
						<a href="{% url 'workshop:edit' event.id %}" class="btn btn-info">
							Edit
						</a>
					</div>
					{% endif %}
					
					{% if event.user != user.user_member %}
						<div class="panel-footer">
						{% if event in user.event_set.all %}
								Enrolled
						{% else %}
							<a href="{% url 'workshop:enroll' event.id %}" class="btn btn-primary">
								Enroll Now
							</a>
						{% endif %}
						</div>
					{% endif %}
				</div>
			</div>
		{% endfor %}
	{% else %}
		<p>No Events Yet</p>
	{% endif %}
	</div>
{% endblock %}

src/templates/workshop/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block head_extra %}
{{ form.media }}
{%endblock head_extra %}


{% block title %} Create Event | {{ block.super }} {% endblock %}

{% block content %}

	{# block.super renders the superblock content #}
	{{ block.super }}
	
	<div class="col-md-10 col-md-offset-1">
		<h2>{{ heading }}</h2>
		<form action="" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form|crispy }}
			<button type="submit">Submit</button>
		</form>
	</div>
{% endblock %}

src/templates/workshop/venue_list.html
{% extends "base.html" %}

{% block title %} Events List | {{ block.super }} {% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-offset-8 col-md-4">
			<a class="btn btn-primary btn-block" href="{% url 'workshop:venue_create'%}">Add Venue</a>
		</div>
	</div>
	<br>
	<div class="row">
	{% if venues %}
		{% for venue in venues %}
			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						<a href="{% url 'workshop:venue_detail' venue.id %}">
						{{ venue.venueName }}
						</a>
					</div>
					<div class="panel-body">
						{{ venue.summary }}
						<br>
						{{ venue.website }} | {{ venue.socialLink }}
					</div>
				</div>
			</div>
		{% endfor %}
	{% else %}
		<p>No venue Yet</p>

	{% endif %}
	</div>
{% endblock %}